In [1]:
!pip install torch


In [1]:
import torch

In [2]:
torch.__version__

'1.12.1'

In [3]:
torch.cuda.is_available()

False

In [4]:
a=torch.rand(2,2)
b=torch.rand(2,2)

In [5]:
a*b

tensor([[0.6264, 0.0123],
        [0.4735, 0.8290]])

In [8]:
h=torch.randn(1)
h

tensor([0.1810])

In [14]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
#Forward Propogation

a=torch.tensor([2])
b=torch.tensor([2])
c=torch.tensor([-2])
d=torch.tensor([-4])

e=a+b
f=c*d
g=e+f

print(e,f,g)

tensor([4]) tensor([8]) tensor([12])


In [18]:
#numpy to tensor

import numpy as np


torch.from_numpy(np.array([1,12,23]))

tensor([ 1, 12, 23], dtype=torch.int32)

In [24]:
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[6,7,8],[9,10,12]])
torch.add(a,b,out=c)

C:\Users\hemanth\AppData\Local\Temp\ipykernel_16068\3012692462.py:3: UserWarning: An output with one or more elements was resized since it had shape [1], which does not match the required output shape [2, 3]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  C:\b\abs_bao0hdcrdh\croot\pytorch_1675190257512\work\aten\src\ATen\native\Resize.cpp:24.)
  torch.add(a,b,out=c)


tensor([[ 7,  9, 11],
        [13, 15, 18]])

In [25]:
c

tensor([[ 7,  9, 11],
        [13, 15, 18]])

In [26]:
a.mul(b)

tensor([[ 6, 14, 24],
        [36, 50, 72]])

In [28]:
x=torch.tensor([1,3,4])
y=torch.tensor([6,4,8])
x.dot(y)

tensor(50)

In [31]:
d=torch.tensor([[1,2,3],
               [4,5,6]])
e=torch.tensor([[5,6],
               [8,9],
               [11,9]])
d.matmul(e)

tensor([[ 54,  51],
        [126, 123]])

In [32]:
d@e

tensor([[ 54,  51],
        [126, 123]])

In [46]:
x=torch.tensor(4,requires_grad=True,dtype=float)

In [47]:
x

tensor(4., dtype=torch.float64, requires_grad=True)

In [48]:
y=x**2

In [49]:
#Back-propogation
y.backward()

In [50]:
x.grad

tensor(8., dtype=torch.float64)

In [52]:
a=torch.tensor(6,requires_grad=True,dtype=float)
b=torch.tensor(5,requires_grad=True,dtype=float)
c=torch.tensor(9,requires_grad=True,dtype=float)

d=a+b
e=c+d

e.backward()

In [57]:
a.grad

tensor(1., dtype=torch.float64)

In [59]:
x=torch.tensor([[1,2,3],
               [4,5,6]],requires_grad=True,dtype=float)

y=x**2+x**3

y

tensor([[  2.,  12.,  36.],
        [ 80., 150., 252.]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [61]:
z=y.sum()

In [62]:
z

tensor(532., dtype=torch.float64, grad_fn=<SumBackward0>)

In [63]:
z.backward()

In [68]:
x.grad

tensor([[  5.,  16.,  33.],
        [ 56.,  85., 120.]], dtype=torch.float64)